@echo off
:: Define the output directory for models
set modelDirectory=./models

:: Create the directory if it doesn't exist
if not exist "%modelDirectory%" (
    mkdir "%modelDirectory%"
)

:: Create tbl_users model file
echo import { Model } from '@nozbe/watermelondb'; > "%modelDirectory%\User.js"
echo import { field, date, children } from '@nozbe/watermelondb/decorators'; >> "%modelDirectory%\User.js"
echo. >> "%modelDirectory%\User.js"
echo class User extends Model { >> "%modelDirectory%\User.js"
echo     static table = 'tbl_users'; >> "%modelDirectory%\User.js"
echo. >> "%modelDirectory%\User.js"
echo     @field('uuid') uuid; >> "%modelDirectory%\User.js"
echo     @field('first_name') firstName; >> "%modelDirectory%\User.js"
echo     @field('middle_name') middleName; >> "%modelDirectory%\User.js"
echo     @field('last_name') lastName; >> "%modelDirectory%\User.js"
echo     @field('suffix') suffix; >> "%modelDirectory%\User.js"
echo     @field('role') role; >> "%modelDirectory%\User.js"
echo     @field('is_exist') isExist; >> "%modelDirectory%\User.js"
echo     @date('created_at') createdAt; >> "%modelDirectory%\User.js"
echo     @date('updated_at') updatedAt; >> "%modelDirectory%\User.js"
echo. >> "%modelDirectory%\User.js"
echo     @children('tbl_customer') customers; >> "%modelDirectory%\User.js"
echo     @children('tbl_article_nominal') articlesNominal; >> "%modelDirectory%\User.js"
echo     @children('tbl_article_min') articlesMin; >> "%modelDirectory%\User.js"
echo     @children('tbl_article_max') articlesMax; >> "%modelDirectory%\User.js"
echo     @children('tbl_article') articles; >> "%modelDirectory%\User.js"
echo     @children('tbl_orders_form') ordersForms; >> "%modelDirectory%\User.js"
echo     @children('tbl_production') productions; >> "%modelDirectory%\User.js"
echo     @children('tbl_laboratory') laboratories; >> "%modelDirectory%\User.js"
echo     @children('tbl_measurement') measurements; >> "%modelDirectory%\User.js"
echo     @children('tbl_proofing') proofings; >> "%modelDirectory%\User.js"
echo     @children('tbl_assignee_history') assigneeHistory; >> "%modelDirectory%\User.js"
echo } >> "%modelDirectory%\User.js"
echo. >> "%modelDirectory%\User.js"
echo export default User; >> "%modelDirectory%\User.js"

:: Create tbl_customer model file
echo import { Model } from '@nozbe/watermelondb'; > "%modelDirectory%\Customer.js"
echo import { field, date, parent } from '@nozbe/watermelondb/decorators'; >> "%modelDirectory%\Customer.js"
echo. >> "%modelDirectory%\Customer.js"
echo class Customer extends Model { >> "%modelDirectory%\Customer.js"
echo     static table = 'tbl_customer'; >> "%modelDirectory%\Customer.js"
echo. >> "%modelDirectory%\Customer.js"
echo     @field('id') id; >> "%modelDirectory%\Customer.js"
echo     @field('first_name') firstName; >> "%modelDirectory%\Customer.js"
echo     @field('middle_name') middleName; >> "%modelDirectory%\Customer.js"
echo     @field('last_name') lastName; >> "%modelDirectory%\Customer.js"
echo     @field('email') email; >> "%modelDirectory%\Customer.js"
echo     @field('is_exist') isExist; >> "%modelDirectory%\Customer.js"
echo     @field('user_id') userId; >> "%modelDirectory%\Customer.js"
echo     @date('created_at') createdAt; >> "%modelDirectory%\Customer.js"
echo     @date('updated_at') updatedAt; >> "%modelDirectory%\Customer.js"
echo. >> "%modelDirectory%\Customer.js"
echo     @parent('user_id') user; >> "%modelDirectory%\Customer.js"
echo } >> "%modelDirectory%\Customer.js"
echo. >> "%modelDirectory%\Customer.js"
echo export default Customer; >> "%modelDirectory%\Customer.js"

:: Create tbl_article_nominal model file
echo import { Model } from '@nozbe/watermelondb'; > "%modelDirectory%\ArticleNominal.js"
echo import { field, date, parent } from '@nozbe/watermelondb/decorators'; >> "%modelDirectory%\ArticleNominal.js"
echo. >> "%modelDirectory%\ArticleNominal.js"
echo class ArticleNominal extends Model { >> "%modelDirectory%\ArticleNominal.js"
echo     static table = 'tbl_article_nominal'; >> "%modelDirectory%\ArticleNominal.js"
echo. >> "%modelDirectory%\ArticleNominal.js"
echo     @field('id') id; >> "%modelDirectory%\ArticleNominal.js"
echo     @field('length') length; >> "%modelDirectory%\ArticleNominal.js"
echo     @field('inside_diameter') insideDiameter; >> "%modelDirectory%\ArticleNominal.js"
echo     @field('outside_diameter') outsideDiameter; >> "%modelDirectory%\ArticleNominal.js"
echo     @field('flat_crush') flatCrush; >> "%modelDirectory%\ArticleNominal.js"
echo     @field('h20') h20; >> "%modelDirectory%\ArticleNominal.js"
echo     @field('is_exist') isExist; >> "%modelDirectory%\ArticleNominal.js"
echo     @field('user_id') userId; >> "%modelDirectory%\ArticleNominal.js"
echo     @date('created_at') createdAt; >> "%modelDirectory%\ArticleNominal.js"
echo     @date('updated_at') updatedAt; >> "%modelDirectory%\ArticleNominal.js"
echo. >> "%modelDirectory%\ArticleNominal.js"
echo     @parent('user_id') user; >> "%modelDirectory%\ArticleNominal.js"
echo } >> "%modelDirectory%\ArticleNominal.js"
echo. >> "%modelDirectory%\ArticleNominal.js"
echo export default ArticleNominal; >> "%modelDirectory%\ArticleNominal.js"

:: Create tbl_article_min model file
echo import { Model } from '@nozbe/watermelondb'; > "%modelDirectory%\ArticleMin.js"
echo import { field, date, parent } from '@nozbe/watermelondb/decorators'; >> "%modelDirectory%\ArticleMin.js"
echo. >> "%modelDirectory%\ArticleMin.js"
echo class ArticleMin extends Model { >> "%modelDirectory%\ArticleMin.js"
echo     static table = 'tbl_article_min'; >> "%modelDirectory%\ArticleMin.js"
echo. >> "%modelDirectory%\ArticleMin.js"
echo     @field('id') id; >> "%modelDirectory%\ArticleMin.js"
echo     @field('length') length; >> "%modelDirectory%\ArticleMin.js"
echo     @field('inside_diameter') insideDiameter; >> "%modelDirectory%\ArticleMin.js"
echo     @field('outside_diameter') outsideDiameter; >> "%modelDirectory%\ArticleMin.js"
echo     @field('flat_crush') flatCrush; >> "%modelDirectory%\ArticleMin.js"
echo     @field('h20') h20; >> "%modelDirectory%\ArticleMin.js"
echo     @field('is_exist') isExist; >> "%modelDirectory%\ArticleMin.js"
echo     @field('user_id') userId; >> "%modelDirectory%\ArticleMin.js"
echo     @date('created_at') createdAt; >> "%modelDirectory%\ArticleMin.js"
echo     @date('updated_at') updatedAt; >> "%modelDirectory%\ArticleMin.js"
echo. >> "%modelDirectory%\ArticleMin.js"
echo     @parent('user_id') user; >> "%modelDirectory%\ArticleMin.js"
echo } >> "%modelDirectory%\ArticleMin.js"
echo. >> "%modelDirectory%\ArticleMin.js"
echo export default ArticleMin; >> "%modelDirectory%\ArticleMin.js"

:: Create tbl_article_max model file
echo import { Model } from '@nozbe/watermelondb'; > "%modelDirectory%\ArticleMax.js"
echo import { field, date, parent } from '@nozbe/watermelondb/decorators'; >> "%modelDirectory%\ArticleMax.js"
echo. >> "%modelDirectory%\ArticleMax.js"
echo class ArticleMax extends Model { >> "%modelDirectory%\ArticleMax.js"
echo     static table = 'tbl_article_max'; >> "%modelDirectory%\ArticleMax.js"
echo. >> "%modelDirectory%\ArticleMax.js"
echo     @field('id') id; >> "%modelDirectory%\ArticleMax.js"
echo     @field('length') length; >> "%modelDirectory%\ArticleMax.js"
echo     @field('inside_diameter') insideDiameter; >> "%modelDirectory%\ArticleMax.js"
echo     @field('outside_diameter') outsideDiameter; >> "%modelDirectory%\ArticleMax.js"
echo     @field('flat_crush') flatCrush; >> "%modelDirectory%\ArticleMax.js"
echo     @field('h20') h20; >> "%modelDirectory%\ArticleMax.js"
echo     @field('is_exist') isExist; >> "%modelDirectory%\ArticleMax.js"
echo     @field('user_id') userId; >> "%modelDirectory%\ArticleMax.js"
echo     @date('created_at') createdAt; >> "%modelDirectory%\ArticleMax.js"
echo     @date('updated_at') updatedAt; >> "%modelDirectory%\ArticleMax.js"
echo. >> "%modelDirectory%\ArticleMax.js"
echo     @parent('user_id') user; >> "%modelDirectory%\ArticleMax.js"
echo } >> "%modelDirectory%\ArticleMax.js"
echo. >> "%modelDirectory%\ArticleMax.js"
echo export default ArticleMax; >> "%modelDirectory%\ArticleMax.js"

:: Repeat similar steps for tbl_orders_form, tbl_production, tbl_laboratory, etc.

:: Create tbl_orders_form model file
echo import { Model } from '@nozbe/watermelondb'; > "%modelDirectory%\OrdersForm.js"
echo import { field, date, parent } from '@nozbe/watermelondb/decorators'; >> "%modelDirectory%\OrdersForm.js"
echo. >> "%modelDirectory%\OrdersForm.js"
echo class OrdersForm extends Model { >> "%modelDirectory%\OrdersForm.js"
echo     static table = 'tbl_orders_form'; >> "%modelDirectory%\OrdersForm.js"
echo. >> "%modelDirectory%\OrdersForm.js"
echo     @field('order_number') orderNumber; >> "%modelDirectory%\OrdersForm.js"
echo     @field('customer_id') customerId; >> "%modelDirectory%\OrdersForm.js"
echo     @date('created_at') createdAt; >> "%modelDirectory%\OrdersForm.js"
echo     @date('updated_at') updatedAt; >> "%modelDirectory%\OrdersForm.js"
echo. >> "%modelDirectory%\OrdersForm.js"
echo     @parent('customer_id') customer; >> "%modelDirectory%\OrdersForm.js"
echo } >> "%modelDirectory%\OrdersForm.js"
echo. >> "%modelDirectory%\OrdersForm.js"
echo export default OrdersForm; >> "%modelDirectory%\OrdersForm.js"

:: Add similar steps for other models as needed (tbl_production, tbl_laboratory, etc.)

:: End the script
echo Models creation completed.
pause
